import '../core/config/shipway_config.dart';
import 'generated_file.dart';

/// The Ruby both generated Fastfiles share.
///
/// Rendered into each platform's file rather than factored into a root
/// `Fastfile` the two import. A generated file that can be read start to finish
/// without following an include is easier to review, and shipway rewrites both
/// together so they cannot drift.
abstract final class FastlaneRuby {
  /// The header every generated Fastfile carries.
  static String header(String platform) =>
      '''
# Generated by shipway. Edit shipway.yaml and re-run `shipway generate`
# instead of changing this file.
#
# Every credential is read from ENV. If a lane below needs a value that is not
# set, it fails saying which one.

require 'shellwords'

default_platform(:$platform)
''';

  /// The `FLAVORS` table, as data rather than literals repeated in each lane.
  ///
  /// [extra] adds per-platform keys — a bundle id on iOS, a package name on
  /// Android — to the entrypoint every platform needs.
  static String flavorTable(
    ResolvedApp app,
    Map<String, String> Function(ResolvedFlavor flavor) extra,
  ) {
    final rows = <String>[
      for (final flavor in app.flavors)
        '  "${flavor.name}" => { '
            '${<String>[for (final entry in extra(flavor).entries) '${entry.key}: "${entry.value}"', 'entrypoint: "${flavor.entrypoint}"'].join(', ')} },',
    ];

    return '''
FLAVORS = {
${rows.join('\n')}
}.freeze

def flavor_config(flavor)
  FLAVORS.fetch(flavor) do
    UI.user_error!("Unknown flavor #{flavor.inspect}. Expected one of: #{FLAVORS.keys.join(', ')}")
  end
end

def require_flavor(options)
  options.fetch(:flavor) do
    UI.user_error!("Pass flavor:. Expected one of: #{FLAVORS.keys.join(', ')}")
  end
end
''';
  }

  /// Path helpers and the environment guard.
  static String helpers() => r'''
def project_root
  @project_root ||= File.expand_path("../..", __dir__)
end

def root_path(*segments)
  File.join(project_root, *segments)
end

def require_env(*names)
  missing = names.flatten.select { |name| ENV[name].to_s.strip.empty? }
  return if missing.empty?

  UI.user_error!("Missing required environment variable(s): #{missing.join(', ')}")
end

def require_file(path, hint)
  return if File.exist?(path)

  UI.user_error!("Required file not found: #{path}\n#{hint}")
end
''';

  /// One place that knows how to invoke `flutter build`.
  ///
  /// Shared because the ways of getting it wrong are silent: without
  /// `--target` Flutter compiles `lib/main.dart` under the flavor's identity,
  /// and without `--dart-define-from-file` it builds against the wrong backend.
  /// Neither fails, so neither can be caught downstream.
  static String flutterBuild() => r'''
# The dart-defines file is passed only when it exists: a flavor may
# legitimately have none, and naming a missing one fails the build.
def flutter_build(type:, flavor:, entrypoint:, version: nil, build: nil, extra: [])
  defines = root_path("dart_defines", "#{flavor}.json")

  args = [
    "flutter build #{type}",
    "--release",
    "--flavor #{flavor.shellescape}",
    # Passed explicitly so the artifact carries the number the release lane
    # resolved, rather than whatever pubspec happened to say. A build stamped
    # with a different number than the one the store was told to expect is a
    # duplicate-build error nobody can trace.
    *(version ? ["--build-name #{version.shellescape}"] : []),
    *(build ? ["--build-number #{build.shellescape}"] : []),
    # Never omitted. Without it Flutter builds lib/main.dart under this
    # flavor's identity: the wrong app, and the build succeeds.
    "--target #{entrypoint.shellescape}",
    *(File.exist?(defines) ? ["--dart-define-from-file #{defines.shellescape}"] : []),
    *extra
  ]

  sh("cd #{project_root.shellescape} && #{args.join(' ')}")
end
''';

  /// Where `changelog_from: file` reads from, at the project root.
  ///
  /// A convention rather than a config field: one more path to configure buys
  /// nothing over a name everybody can guess.
  static const String changelogFileName = 'CHANGELOG_NEXT.md';

  /// A Ruby method returning release notes from wherever `changelog_from`
  /// says, or nil.
  ///
  /// Shared by TestFlight and Firebase so the two cannot disagree about what
  /// `git` means. [function] names the method, [configKey] is the field it
  /// came from — written into the output so a reader can find it — and
  /// [question] is what `prompt` asks.
  static String changelog({
    required ChangelogSource source,
    required String function,
    required String configKey,
    required String question,
  }) => switch (source) {
    ChangelogSource.git => _changelogFromGit(function, configKey),
    ChangelogSource.file => _changelogFromFile(function, configKey),
    ChangelogSource.prompt => _changelogFromPrompt(
      function,
      configKey,
      question,
    ),
  };

  static String _changelogFromGit(String function, String configKey) =>
      '''
# $configKey: git
def $function(override = nil)
  return override unless override.to_s.strip.empty?

  # A repository with no tag yet has no "since last release" to describe, and
  # the action raises rather than returning nothing. The first release having
  # no changelog is the right answer, not a failed upload.
  notes = begin
    changelog_from_git_commits(
      merge_commit_filtering: "exclude_merges",
      pretty: "- %s"
    )
  rescue StandardError => e
    UI.important("No changelog from git (#{e.message}). Uploading without one.")
    nil
  end

  notes.to_s.strip.empty? ? nil : notes
end
''';

  static String _changelogFromFile(String function, String configKey) =>
      '''
# $configKey: file
def $function(override = nil)
  return override unless override.to_s.strip.empty?

  path = root_path("$changelogFileName")
  unless File.exist?(path)
    UI.important("No $changelogFileName to read. Uploading without a changelog.")
    return nil
  end

  notes = File.read(path).strip
  notes.empty? ? nil : notes
end
''';

  /// Written with single backslashes in the Ruby. An earlier raw-string
  /// version emitted `\\` at the end of a line, which is a Ruby syntax error,
  /// so a config choosing `prompt` produced a Fastfile that could not load.
  static String _changelogFromPrompt(
    String function,
    String configKey,
    String question,
  ) =>
      '''
# $configKey: prompt
def $function(override = nil)
  return override unless override.to_s.strip.empty?

  # A prompt on a runner is a hang, which burns the job timeout and reports
  # nothing. Saying so is strictly better.
  if is_ci
    UI.user_error!("changelog_from: prompt cannot run unattended. Pass " \\
                   "changelog:\\"...\\" to the lane, or use changelog_from: git.")
  end

  notes = UI.input("$question")
  notes.to_s.strip.empty? ? nil : notes
end
''';
}
